version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USERS_SERVICE_URL=http://users-service:8081
      - CARS_SERVICE_URL=http://cars-service:8082
      - BOOKINGS_SERVICE_URL=http://bookings-service:8083
    depends_on:
      - users-service
      - cars-service
      - bookings-service

  # Users Service
  users-service:
    build:
      context: ./services/users-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=carrental
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - postgres

  # Cars Service
  cars-service:
    build:
      context: ./services/cars-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=carrental
    depends_on:
      - postgres

  # Bookings Service
  bookings-service:
    build:
      context: ./services/bookings-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=carrental
      - CARS_SERVICE_URL=http://cars-service:8082
    depends_on:
      - postgres
      - cars-service

  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=carrental
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
